accounts/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import LogoutView
from .views import login_page, register_page, guest_login_view

urlpatterns = [
    url(r'^login/$', login_page, name="login_page"),
    url(r'^logout/$', LogoutView.as_view(), name="logout_page"),
    url(r'^register/$', register_page, name="register_page"),
    url(r'^guest-login/$', guest_login_view, name="guest_login"),
]

carts/urls.py
from django.conf.urls import url
from .views import cart_home, cart_update, checkout_home


urlpatterns = [
    url(r'^$', cart_home, name="cart_home"),
    url(r'^checkout/$', checkout_home, name="checkout"),
    url(r'^update/$', cart_update, name="cart_update"),
]

ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import home_page, about_page, contact_page

urlpatterns = [
    url(r'^contact/$', contact_page, name="contact_page"),
    url(r'^about/$', about_page, name="about_page"),
    url(r'^$', home_page, name="home_page"),
    url(r'^accounts/', include('accounts.urls', namespace='accounts_page')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^cart/', include('carts.urls', namespace='cart_page')),
    url(r'^search/', include('search.urls', namespace='search_page')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url
from .views import (
    ProductListView,
    ProductDetailSlugView,
)


urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='products_list'),
    url(r'^product/(?P<slug>[\w-]+)/$',
        ProductDetailSlugView.as_view(), name="detailproduct"),
]

templates/base/css.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.11/css/all.css" integrity="sha384-p2jx59pefphTFIpeqCcISO9MdVfIm4pNnsL08A6v5vaQc4owkQqxMV8kg4Yvhaw/" crossorigin="anonymous">

templates/base/js.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

templates/base/navbar.html
{% load static %}
{% url 'home_page' as home_url %}
{% url 'contact_page' as contact_url %}
{% url 'accounts_page:login_page' as login_url %}
{% url 'accounts_page:logout_page' as logout_url %}
{% url 'accounts_page:register_page' as register_url %}
{% url 'products:products_list' as products_url %}
{% url 'cart_page:cart_home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">{{ brand_name }}</a>
    <ul class="navbar-nav mr-auto ml-auto mt-2 mt-lg-0">
      <li class="nav-item {% if request.path == home_url %} active {% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == products_url %} active {% endif %}">
        <a class="nav-link" href="{{ products_url }}">Products</a>
      </li>
      <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == cart_url %} active {% endif %}">
        <a class="nav-link" href="{{ cart_url }}">{{ request.session.cart_items }}
          <i class="fas fa-shopping-cart"></i>
        </a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ logout_url }}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item {% if request.path == login_url %} active {% endif %}">
          <a class="nav-link" href="{{ login_url }}">Login</a>
        </li>
      <li class="nav-item {% if request.path == register_url %} active {% endif %}">
        <a class="nav-link" href="{{ register_url }}">Sigup</a>
      </li>
      {% endif %}
    </ul>

    {% include 'search/snippets/search-form.html' %}
  </div>
</nav>