carts/urls.py
from django.conf.urls import url
from .views import cart_home, cart_update, checkout_home


urlpatterns = [
    url(r'^$', cart_home, name="cart_home"),
    url(r'^checkout/$', checkout_home, name="checkout"),
    url(r'^update/$', cart_update, name="cart_update"),
]

ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import home_page, about_page, contact_page

urlpatterns = [
    url(r'^contact/$', contact_page, name="contact_page"),
    url(r'^about/$', about_page, name="about_page"),
    url(r'^$', home_page, name="home_page"),
    url(r'^accounts/', include('accounts.urls', namespace='accounts_page')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^cart/', include('carts.urls', namespace='cart_page')),
    url(r'^search/', include('search.urls', namespace='search_page')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from decimal import Decimal
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save, post_save, m2m_changed
from products.models import Product

User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = self.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(
        default=0.00, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) + \
            Decimal(1.23)  # shipping or vat (23% ivA)
    else:
        instance.total = 0.00


pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from django.shortcuts import render, redirect
from accounts.forms import LoginForm, GuestForm
from billing.models import BillingProfile
from products.models import Product
from orders.models import Order
from accounts.models import GuestEmail
from .models import Cart


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    # print(dir(request.session)) # see available 'fields'
    template = 'cart/cart_home.html'
    ctx = {
        'cart': cart_obj
    }
    return render(request, template, ctx)


def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            # TODO show message to user
            return redirect('cart_page:cart_home')
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
        else:
            # cart_obj.products.add(product_id)
            cart_obj.products.add(product_obj)
        request.session['cart_items'] = cart_obj.products.count()
    return redirect('cart_page:cart_home')
    # return redirect(product_obj.get_absolute_url())


def checkout_home(request):
    template = 'cart/checkout.html'
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect('cart_page:cart_home')
    else:
        order_obj, new_order_obj = Order.objects.get_or_create(cart=cart_obj)
    user = request.user
    billing_profile = None
    login_form = LoginForm()
    guest_form = GuestForm()
    guest_email_id = request.session.get('guest_email_id')
    if user.is_authenticated():
        # if user.email:
        billing_profile, billing_profile_created = BillingProfile.objects.get_or_create(user=user, email=user.email)
    elif guest_email_id is not None:
        guest_email_obj = GuestEmail.objects.get(id=guest_email_id)
        billing_guest_profile, billing_guest_profile_created = BillingProfile.objects.get_or_create(
            email=guest_email_obj.email)
    else:
        pass
    ctx = {
        'object': order_obj,
        'billing_profile': billing_profile,
        'login_form': login_form,
        'guest_form': guest_form,
    }
    return render(request, template, ctx)

carts/templates/cart/cart_home.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <h1>Cart</h1>

    {% if cart.products.exists %}
        <table class="table">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Product Name</th>
            <th scope="col">Product Price</th>
            </tr>
        </thead>
        <tbody>
            {% for product in cart.products.all %}
            <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a> 
                {% include "snippets/update-cart.html" with product=product cart=cart in_cart=True %}            
            </td>
            <td>{{ product.price }}</td>
            </tr>          
            {% endfor %}

            <tr>
            <td colspan="2"></td>
            <td><b>Subtotal: </b> {{ cart.subtotal }}</td>
            </tr>
            <tr>
            <td colspan="2"></td>
            <td><b>total: </b> {{ cart.total }}</td>
            </tr>
            <tr>
            <td colspan="2"></td>
            <td><a class="btn btn-block btn-success" href="{% url 'cart_page:checkout' %}" >Checkout</a></td>
            </tr>
        </tbody>
        </table>
    {% else %}
        <p class="lead"> Cart is empty </p>
    {% endif %}
    </div>
{% endblock content %}
    

carts/templates/cart/checkout.html
{% extends 'base.html' %}


{% block content %}

{% if not billing_profile %}
	<div class="container">
		<div class="row text-center">
			<div class="col-12 col-md-6">
				<p class="lead">Login</p>
				{% include "snippets/form.html" with form=login_form next_url=request.build_absolute_uri %}
			</div>
			<div class="col-12 col-md-6">
				Continue as Guest
				{% url 'guest_login' as guest_login_url %}
                {% include "snippets/form.html" with form=guest_form next_url=request.build_absolute_uri action_url=guest_login_url %}
			</div>
		</div>
	</div>
{% else %}

    <div class="container">
        <h1>Checkout</h1>
        <p>Cart Total: {{ object.cart.total }}</p>
        <p>Shipping Total: {{ object.shipping_total }} </p>
        <p>Order Total: {{ object.total }} </p>
    </div>
{% endif %}
{% endblock content %}
    